use_frameworks!

platform :ios, '9.0'

target 'DSHSecondPrintPod_Example' do
  pod 'DSHSecondPrintPod', :path => '../'

  target 'DSHSecondPrintPod_Tests' do
    inherit! :search_paths

    
  end
end
